kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: enphase-pvc
  namespace: solar-monitoring
spec:
  storageClassName: cinder-standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
