apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: solar-monitoring
  name: enphase-test
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app.kubernetes.io/name: enphase-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: enphase-test
    spec:
      containers:
        - name: enphase-test
          image: ericvaandering/solar-monitoring:0.0.2
          imagePullPolicy: Always
          volumeMounts:
            - name: enphase-data
              mountPath: /var/lib/enphase
          command: ["sleep"]
          args: ["3600"]
          env:
              - name: API_KEY
                valueFrom:
                  secretKeyRef:
                    key: enphase_api_key
                    name: enphase-secrets
              - name: AUTH_CREDENTIALS
                valueFrom:
                  secretKeyRef:
                    key: enphase_credentials
                    name: enphase-secrets
      volumes:
        - name: enphase-data
          persistentVolumeClaim:
            claimName: enphase-pvc

